"""empty message

Revision ID: 03c2efc2a42e
Revises: 4d6e92fc32da
Create Date: 2024-06-05 13:22:32.221059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c2efc2a42e'
down_revision = '4d6e92fc32da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likerecipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipi_id', sa.Integer(), nullable=False),
    sa.Column('like_now', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likerecipes')
    # ### end Alembic commands ###
