"""empty message

Revision ID: 4d6e92fc32da
Revises: db39d45330bb
Create Date: 2024-06-05 13:20:02.940314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6e92fc32da'
down_revision = 'db39d45330bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likerecipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likerecipes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipi_id', sa.INTEGER(), nullable=False),
    sa.Column('like_now', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
