"""empty message

Revision ID: 80c6a4b9907a
Revises: 8f7b01420082
Create Date: 2024-06-04 23:34:10.386059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c6a4b9907a'
down_revision = '8f7b01420082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likerecipes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipi_id', sa.Integer(), nullable=False),
    sa.Column('like_now', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likerecipes')
    # ### end Alembic commands ###
