"""empty message

Revision ID: db39d45330bb
Revises: f5befb749cda
Create Date: 2024-06-05 13:17:39.257956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db39d45330bb'
down_revision = 'f5befb749cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likerecipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likerecipes', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
