"""empty message

Revision ID: e885ede1d4f1
Revises: e9587d741af8
Create Date: 2024-06-04 20:36:35.414877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e885ede1d4f1'
down_revision = 'e9587d741af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likerecipes')
    op.drop_table('aiueo_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiueo_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aiueo', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likerecipes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipi_id', sa.INTEGER(), nullable=False),
    sa.Column('like_now', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipi_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
