"""empty message

Revision ID: e9587d741af8
Revises: 73a6369c209a
Create Date: 2024-06-04 20:34:00.264143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9587d741af8'
down_revision = '73a6369c209a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiueo_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aiueo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aiueo_table')
    # ### end Alembic commands ###
