"""empty message

Revision ID: ea4f06cb8e23
Revises: d2e2ccef1b80
Create Date: 2023-08-28 15:06:06.019426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4f06cb8e23'
down_revision = 'd2e2ccef1b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('how_to', sa.String(), nullable=True),
    sa.Column('p', sa.Integer(), nullable=False),
    sa.Column('f', sa.Integer(), nullable=False),
    sa.Column('c', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_username'))

    op.drop_table('recipes')
    # ### end Alembic commands ###
