"""empty message

Revision ID: f5befb749cda
Revises: 80c6a4b9907a
Create Date: 2024-06-05 00:03:07.248409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5befb749cda'
down_revision = '80c6a4b9907a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aiueo_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiueo_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aiueo', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
