"""empty message

Revision ID: f9b9f34b6027
Revises: 571ff39d5c4e
Create Date: 2024-06-04 20:26:58.807691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b9f34b6027'
down_revision = '571ff39d5c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likerecipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likerecipes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipi_id', sa.INTEGER(), nullable=False),
    sa.Column('like_now', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipi_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
